savedir: SCAPE_5k
DataLoader: SCAPE_5K_train_DataLoader
root: data/SCAPE_5k/off
vts: data/SCAPE_5k/corres
geod: data/SCAPE_5k/geod
num_of_points: 2000
Loss: BIJ_KL_loss
save_ckpt_name: best_basis.pth
n_feat: 20
lr: 0.002
n_epochs: 600
device: cuda:0
batch_size: 3
step_size: 50
gamma: 0.7
z_dim: 64
hidden_size: 256
n_knn: 50
pooling: max

